database:
  username: dart
  password: dart
  host: localhost
  port: 5432
  databaseName: dart_test
firebaseServerKey: AAAAuDH1ASc:APA91bEL9xI3dwWvShoXc6VO6MSVbQC-mqbMn-uEwY895LL4KUiusteqqk1tzEO837fViuaSK7HkKh6Mydx02xWuWIKyJD7c85LXGFkRNj6ynMZHUgwBlyegeT8vi3cNrBJPWVN_3Lz2
stripeKey: sk_test_Euh1ccfoKAYDZYDHin8ltxnt00utQpfnmF
mailJetKey: ca64979711f0431bba36dfc8cbb94207
mailJetSecret: 723b954dd71be011c50e079a14cdf4a2